config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root 'users#index'

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users, :only => [:new, :create, :show]
  resources :sessions, :only => [:create]

  resources :collections, :only => [:index, :new, :create, :edit, :update, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/collection.rb
class Collection < ApplicationRecord
  enum status: { wait_approve: 0, approved_y: 1, approved_n: 2 }

  belongs_to :user, counter_cache: true

  validates :title,
            :presence => true,
            :length => {:within => 5..20}

  validates :content,
            :presence => true,
            :length => {:within => 10..200}



end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]
  before_filter :require_sign_in, :only => [:new, :create, :edit, :update]

  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.all
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)
    @collection.user = current_user

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:title, :content, :user_id)
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
  def available_collections
    return @collections if @collections
    # @collections = Collection.available.collect{|collection| [collection.title, collection.id]}
    @collections = Collection.all.collect{|collection| [collection.title, collection.id]}
  end


end

app/views/collections/_form.html.erb
<%= form_for(collection) do |f| %>
  <% if collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h1>Editing Collection</h1>

<%= render 'form', collection: @collection %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>

app/views/collections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Collections</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @collections.each do |collection| %>
      <tr>
        <td><%= collection.title %></td>
        <td><%= collection.content %></td>
        <td><%= collection.user_id %></td>
        <td><%= link_to 'Show', collection %></td>
        <td><%= link_to 'Edit', edit_collection_path(collection) %></td>
        <td><%= link_to 'Destroy', collection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Collection', new_collection_path %>

app/views/collections/new.html.erb
<h1>New Collection</h1>

<%= render 'form', collection: @collection %>

<%= link_to 'Back', collections_path %>

app/views/collections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @collection.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @collection.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @collection.user.username %>
</p>

<%= link_to 'Edit', edit_collection_path(@collection) %>